#ifndef _GESTURE_H_
#define _GESTUR_H_

// Gesture events
#define MICROBIT_ACCELEROMETER_EVT_NONE                     0
#define MICROBIT_ACCELEROMETER_EVT_TILT_UP                  1
#define MICROBIT_ACCELEROMETER_EVT_TILT_DOWN                2
#define MICROBIT_ACCELEROMETER_EVT_TILT_LEFT                3
#define MICROBIT_ACCELEROMETER_EVT_TILT_RIGHT               4
#define MICROBIT_ACCELEROMETER_EVT_FACE_UP                  5
#define MICROBIT_ACCELEROMETER_EVT_FACE_DOWN                6
#define MICROBIT_ACCELEROMETER_EVT_FREEFALL                 7
#define MICROBIT_ACCELEROMETER_EVT_3G                       8
#define MICROBIT_ACCELEROMETER_EVT_6G                       9
#define MICROBIT_ACCELEROMETER_EVT_8G                       10
#define MICROBIT_ACCELEROMETER_EVT_SHAKE                    11

// Gesture recogniser constants
#define MICROBIT_ACCELEROMETER_REST_TOLERANCE               100
#define MICROBIT_ACCELEROMETER_TILT_TOLERANCE               100
#define MICROBIT_ACCELEROMETER_FREEFALL_TOLERANCE           200
#define MICROBIT_ACCELEROMETER_SHAKE_TOLERANCE              300
#define MICROBIT_ACCELEROMETER_3G_TOLERANCE                 1536
#define MICROBIT_ACCELEROMETER_6G_TOLERANCE                 3072
#define MICROBIT_ACCELEROMETER_8G_TOLERANCE                 4096
#define MICROBIT_ACCELEROMETER_GESTURE_DAMPING              3
#define MICROBIT_ACCELEROMETER_SHAKE_DAMPING                5
#define MICROBIT_ACCELEROMETER_SHAKE_RTX                    15

#define MICROBIT_ACCELEROMETER_REST_THRESHOLD               (MICROBIT_ACCELEROMETER_REST_TOLERANCE * MICROBIT_ACCELEROMETER_REST_TOLERANCE)
#define MICROBIT_ACCELEROMETER_FREEFALL_THRESHOLD           ((uint32_t)MICROBIT_ACCELEROMETER_FREEFALL_TOLERANCE * (int)MICROBIT_ACCELEROMETER_FREEFALL_TOLERANCE)
#define MICROBIT_ACCELEROMETER_3G_THRESHOLD                 ((int)MICROBIT_ACCELEROMETER_3G_TOLERANCE * (int)MICROBIT_ACCELEROMETER_3G_TOLERANCE)
#define MICROBIT_ACCELEROMETER_6G_THRESHOLD                 ((int)MICROBIT_ACCELEROMETER_6G_TOLERANCE * (int)MICROBIT_ACCELEROMETER_6G_TOLERANCE)
#define MICROBIT_ACCELEROMETER_8G_THRESHOLD                 ((int)MICROBIT_ACCELEROMETER_8G_TOLERANCE * (int)MICROBIT_ACCELEROMETER_8G_TOLERANCE)
#define MICROBIT_ACCELEROMETER_SHAKE_COUNT_THRESHOLD        1

// Initialise gesture history
int sigma = 0;
int impulseSigma = 0;
int lastGesture = MICROBIT_ACCELEROMETER_EVT_NONE;
int currentGesture = MICROBIT_ACCELEROMETER_EVT_NONE;
int shake_x = 0;
int shake_y = 0;
int shake_z = 0;
int shake_count = 0;
int shake_timer = 0;
int shake_shaken = 0;
int shake_impulse_3 = 1;
int shake_impulse_6 = 1;
int shake_impulse_8 = 1;
#endif
